---
# tasks file for ansible-role-yum

- name: install repos that are in repos from CentOS
  yum: name={{ item }} state=present
  with_items: centos_releases | default({})

- name: install software that do not need extra configuration
  yum: name={{ item }} state=present
  with_items: unconfigured_packages | default({})

- name: remove software 
  yum: "name={{ item }} state=absent"
  with_items: remove_packages | default({})
