---
# tasks file for ansible-role-yum

- name: install repos that are in repos from CentOS
  yum: name={{ item }} state=present
  with_items: centos_releases | default({})

- name: template in yum.conf on CentOS7 if yum_conf_template is True
  template: src=yum.conf.j2 dest=/etc/yum.conf mode=0644 owner=root group=root backup=yes
  when: yum_conf_template == True and ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: update all the things
  yum: name=* state=latest

- name: install IB software that do not need extra configuration - on nodes with ib interfaces
  yum: name={{ item }} state=present
  with_items: ib_unconfigured_packages | default({})
  when: infiniband_available and ib_unconfigured_packages.0 != ""

- name: install software that do not need extra configuration
  yum: name={{ item }} state=present
  with_items: unconfigured_packages | default({})
  when: unconfigured_packages.0 != ""

- name: remove software 
  yum: "name={{ item }} state=absent"
  with_items: remove_packages | default({})
  when: remove_packages.0 != ""

- name: disable and stop services
  service: "name={{ item }} enabled=no state=stopped"
  with_items: disable_packages | default({})
  when: disable_packages.0 != ""
